baseURL = "https://lctt-linux.netlify.app"
languageCode = "en-us"
title = "Linux Introduction"
theme = "hugo-theme-relearn"

canonifyURLs = true

[params]
  themeVariant = ["lc-light", "lc-dark-blue", "lc-dark-blue-two"]
  editURL = "https://github.com/LaunchCodeEducation/linux/edit/master/content/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.shortcuts]]
  name = "Contributing to this Project"
  url = "/contributing"
  weight = 99998

[[menu.shortcuts]]
  name = "Quality of Life Improvements"
  url = "/quality-of-life"
  weight = 99997
